[book]
authors = ["BoxyUwU"]
language = "en"
src = "src"
title = "Unfair Rust Quiz"

[output.html]
additional-css = ["assets/quiz.css"]
additional-js = ["assets/quiz.js"]
git-repository-url = "https://github.com/BoxyUwU/rust-quiz"
no-section-label = false
playground.runnable = false

[output.html.fold]
enable = true
level = 1
