# We want to pin the precise toolchain used to make sure everything is reproducible.
[toolchain]
channel = "nightly-2025-11-02" # Keep it in in sync with index.md!
profile = "minimal"
components = ["miri", "rust-src"]
